=== VladimirZaets/api-mesh-sources/connector.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://adobe.io/schemas/aio/connectors/0-0-1",
    "title": "connector-schema",
    "description": "A schema for the Adobe Connector",
    "type": "object",
    "properties": {
        "name": {
          "type": "string",
          "description": "The unique connector name"
        },
        "author": {
          "type": "string",
          "description": "The name of the author"
        },
        "version": {
          "type": "string",
          "description": "The version of the connector"
        },
        "description": {
          "type": "string",
          "description": "A description of the connector"
        },
        "variables": {
          "type": ["object", "null"],
          "description": "The list of variables for source"
        },
        "provider": {
          "type": "object",
          "description": "The connector source"
        },
        "files": {
          "type": ["array", "null"],
          "items": {
            "type": "object",
            "properties": {
              "path": {
                "type": "string"
              },
              "content": {
                "type": "string"
              }
            }
          }
        }
    },
    "required":["name", "author", "version", "description", "provider"],
    "additionalProperties" : false
  }

=== VladimirZaets/api-mesh-sources/connectors/CommerceCoreGraph.json
{
  "name": "CommerceCoreGraph",
  "version": "0.0.2",    
  "author": "nrkapoor",
  "description": "Adobe Commerce Core",
  "provider": {
    "name": "CommerceCoreGraph",
    "handler": {
      "graphql": {
        "endpoint": "${ENDPOINT_URL}"
      }
    },
    "transforms": [
      {
        "filterSchema": {
          "mode": "bare",
          "filters": [
            "Query.!category",
            "Query.!customerOrders",
            "Query.!urlResolver",
            "Query.!wishlist",
            "Query.!categoryList",
            "Mutation.!setPaymentMethodAndPlaceOrder",
            "Mutation.!addBundleProductsToCart",
            "Mutation.!addConfigurableProductsToCart",
            "Mutation.!addDownloadableProductsToCart",
            "Mutation.!addSimpleProductsToCart",
            "Mutation.!addVirtualProductsToCart",
            "Mutation.!createCustomer",
            "Mutation.!updateCustomer"
          ]
        }
      }
    ]
  }
}
